# Generated by Django 5.0.6 on 2026-07-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cmspage',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='galleryalbum',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-posted_at']},
        ),
    ]
