-- EduNova Portal Extension #2 — Parent Portal + Admin Portal support tables.
-- Run this AFTER portal_extension_auth_user.sql (which must already be applied).
-- Safe to run multiple times: every statement is IF NOT EXISTS / ADD COLUMN IF NOT EXISTS.

-- ---------------------------------------------------------------------------
-- Staff / HR (backs Admin Portal "Employees" + drivers for Transport)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_employee (
  user_id integer PRIMARY KEY REFERENCES public.auth_user(id) ON DELETE CASCADE,
  employee_code varchar(50) UNIQUE,
  department varchar(50) NOT NULL DEFAULT 'Administration',
  designation varchar(100),
  date_of_joining date,
  monthly_salary numeric,
  is_active boolean NOT NULL DEFAULT true
);

-- ---------------------------------------------------------------------------
-- Transport module (Vehicles / Routes / Allocations / Live location)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_vehicle (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_number varchar(50) UNIQUE NOT NULL,
  capacity integer,
  driver_id integer REFERENCES public.portal_employee(user_id) ON DELETE SET NULL,
  gps_device_id varchar(150) UNIQUE,
  maintenance_status varchar(100) NOT NULL DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS public.portal_route (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_name varchar(150) NOT NULL,
  start_point varchar(200),
  end_point varchar(200)
);

CREATE TABLE IF NOT EXISTS public.portal_transport_allocation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  vehicle_id integer NOT NULL REFERENCES public.portal_vehicle(id) ON DELETE CASCADE,
  route_id integer NOT NULL REFERENCES public.portal_route(id) ON DELETE CASCADE,
  pickup_point varchar(200),
  UNIQUE (student_id)
);

CREATE TABLE IF NOT EXISTS public.portal_live_bus_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id integer NOT NULL REFERENCES public.portal_vehicle(id) ON DELETE CASCADE,
  latitude numeric(9,6) NOT NULL,
  longitude numeric(9,6) NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_live_bus_log_vehicle ON public.portal_live_bus_log(vehicle_id, updated_at DESC);

-- ---------------------------------------------------------------------------
-- Parent-Teacher Meetings + Feedback
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_ptm_booking (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  student_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  meeting_date date NOT NULL,
  time_slot time NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'Scheduled' CHECK (status IN ('Scheduled','Completed','Cancelled')),
  parent_notes text
);

CREATE TABLE IF NOT EXISTS public.portal_parent_feedback (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  category varchar(100) NOT NULL DEFAULT 'General',
  feedback_text text NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'Pending',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Leave requests: allow a parent to submit on behalf of a child
-- ---------------------------------------------------------------------------
ALTER TABLE public.portal_leave ADD COLUMN IF NOT EXISTS submitted_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL;

-- ---------------------------------------------------------------------------
-- Audit log (Admin Portal — every admin-side write goes through log_action())
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  action varchar(100) NOT NULL,
  target_type varchar(100),
  target_id varchar(100),
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON public.portal_audit_log(created_at DESC);

-- ---------------------------------------------------------------------------
-- Link admissions -> the auth_user accounts created once an application is
-- Confirmed, so the Admin Portal can trace "which account did this enquiry
-- turn into" and never double-create logins for the same enquiry.
-- ---------------------------------------------------------------------------
-- NOTE: admissions_admissionenquiry.student_user_id / parent_user_id are
-- added via a real Django migration (apps/admissions/migrations/0002_...),
-- not here — that table is Django-managed (managed=True), unlike the
-- portal_* tables in this file. See CLIENT_READY_RUNBOOK.md for the exact
-- `migrate --fake-initial` steps needed the first time you adopt migrations
-- against a database that already has this table.

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_transport_allocation_student ON public.portal_transport_allocation(student_id);
CREATE INDEX IF NOT EXISTS idx_ptm_booking_parent ON public.portal_ptm_booking(parent_id);
CREATE INDEX IF NOT EXISTS idx_employee_department ON public.portal_employee(department);
