-- EduNova Portal Extension #3 — Facilities & back-office modules that were
-- listed in the client requirements doc but not yet built:
-- Hostel, Inventory, Visitor Management, Alumni Registry, Medical Records.
-- Run this AFTER portal_extension_auth_user.sql and portal_extension_parent_admin.sql
-- (hostel rooms reference portal_employee for the warden).
-- Safe to run multiple times: every statement is IF NOT EXISTS.

-- ---------------------------------------------------------------------------
-- Hostel module
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_hostel (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(150) NOT NULL,
  type varchar(20) NOT NULL DEFAULT 'Boys' CHECK (type IN ('Boys', 'Girls', 'Staff')),
  warden_id integer REFERENCES public.portal_employee(user_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.portal_room (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hostel_id integer NOT NULL REFERENCES public.portal_hostel(id) ON DELETE CASCADE,
  room_number varchar(30) NOT NULL,
  capacity integer NOT NULL DEFAULT 1,
  occupied_beds integer NOT NULL DEFAULT 0,
  UNIQUE (hostel_id, room_number)
);

CREATE TABLE IF NOT EXISTS public.portal_hostel_allocation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  room_id integer NOT NULL REFERENCES public.portal_room(id) ON DELETE CASCADE,
  allocated_date date NOT NULL DEFAULT CURRENT_DATE,
  vacated_date date,
  UNIQUE (student_id, room_id, allocated_date)
);
CREATE INDEX IF NOT EXISTS idx_hostel_allocation_student ON public.portal_hostel_allocation(student_id);

-- ---------------------------------------------------------------------------
-- Inventory module
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_inventory (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_name varchar(200) NOT NULL,
  category varchar(50) NOT NULL DEFAULT 'General',
  quantity integer NOT NULL DEFAULT 0,
  department varchar(100) NOT NULL DEFAULT 'Administration',
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_inventory_department ON public.portal_inventory(department);

-- ---------------------------------------------------------------------------
-- Visitor Management
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_visitor_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_name varchar(150) NOT NULL,
  purpose text NOT NULL,
  host_user_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  id_proof_type varchar(50) NOT NULL DEFAULT 'Other',
  check_in_time timestamptz NOT NULL DEFAULT now(),
  check_out_time timestamptz
);
CREATE INDEX IF NOT EXISTS idx_visitor_log_checkin ON public.portal_visitor_log(check_in_time DESC);

-- ---------------------------------------------------------------------------
-- Alumni Registry
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_alumni (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  graduation_year integer NOT NULL,
  current_occupation varchar(200),
  higher_studies_details text,
  UNIQUE (student_id)
);
CREATE INDEX IF NOT EXISTS idx_alumni_graduation_year ON public.portal_alumni(graduation_year);

-- ---------------------------------------------------------------------------
-- Medical Records
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_medical_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  visit_date date NOT NULL DEFAULT CURRENT_DATE,
  symptoms text NOT NULL,
  treatment_given text NOT NULL,
  doctor_notes text,
  recorded_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_medical_log_student ON public.portal_medical_log(student_id);

-- ---------------------------------------------------------------------------
-- LMS extras: Discussion Forums + Digital Notes (client requirements doc
-- listed both under "Learning Management System" — course/quiz/assignment
-- core was already built, these two were the remaining gap).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_forum_topic (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id integer NOT NULL REFERENCES public.portal_course(id) ON DELETE CASCADE,
  creator_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  title varchar(200) NOT NULL,
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_forum_topic_course ON public.portal_forum_topic(course_id);

CREATE TABLE IF NOT EXISTS public.portal_forum_post (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id integer NOT NULL REFERENCES public.portal_forum_topic(id) ON DELETE CASCADE,
  author_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  post_text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_forum_post_topic ON public.portal_forum_post(topic_id);

CREATE TABLE IF NOT EXISTS public.portal_digital_note (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id integer NOT NULL REFERENCES public.portal_course(id) ON DELETE CASCADE,
  author_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  title varchar(200) NOT NULL,
  body_markdown text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_digital_note_course ON public.portal_digital_note(course_id);

-- Learning analytics needs a per-student, per-content completion record —
-- course_content already exists (portal_extension_auth_user.sql); this is
-- the missing join table that lets "% of course completed" be computed.
CREATE TABLE IF NOT EXISTS public.portal_course_progress (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  content_id integer NOT NULL REFERENCES public.portal_course_content(id) ON DELETE CASCADE,
  is_completed boolean NOT NULL DEFAULT true,
  completed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (student_id, content_id)
);
CREATE INDEX IF NOT EXISTS idx_course_progress_student ON public.portal_course_progress(student_id);
