-- EduNova Portal Extension for the Supabase schema shared in this chat.
-- Run this AFTER your current Django/CMS/admissions schema.
-- It uses Django's existing auth_user table, because your latest schema already contains auth_user.

CREATE TABLE IF NOT EXISTS public.portal_user_profile (
  user_id integer PRIMARY KEY REFERENCES public.auth_user(id) ON DELETE CASCADE,
  user_type varchar(20) NOT NULL CHECK (user_type IN ('Student','Parent','Teacher','Admin','Employee')),
  phone_number varchar(20),
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.portal_parent_profile (
  user_id integer PRIMARY KEY REFERENCES public.auth_user(id) ON DELETE CASCADE,
  father_name varchar(150),
  mother_name varchar(150),
  emergency_contact varchar(20),
  address text,
  is_verified boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.portal_teacher_profile (
  user_id integer PRIMARY KEY REFERENCES public.auth_user(id) ON DELETE CASCADE,
  employee_code varchar(50) UNIQUE,
  qualification varchar(255),
  specialization varchar(150),
  date_of_joining date
);

CREATE TABLE IF NOT EXISTS public.portal_class (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL,
  section varchar(10) NOT NULL,
  curriculum varchar(30) NOT NULL DEFAULT 'CBSE',
  room_number varchar(30),
  UNIQUE (name, section)
);

CREATE TABLE IF NOT EXISTS public.portal_subject (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  subject_code varchar(30) UNIQUE NOT NULL,
  type varchar(30) NOT NULL DEFAULT 'Theory'
);

CREATE TABLE IF NOT EXISTS public.portal_student_profile (
  user_id integer PRIMARY KEY REFERENCES public.auth_user(id) ON DELETE CASCADE,
  parent_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  admission_number varchar(50) UNIQUE NOT NULL,
  qr_id_code varchar(100) UNIQUE,
  date_of_birth date,
  gender varchar(20),
  blood_group varchar(10),
  status varchar(20) NOT NULL DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS public.portal_student_enrollment (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  academic_year varchar(20) NOT NULL,
  roll_number integer,
  UNIQUE (student_id, class_id, academic_year)
);

CREATE TABLE IF NOT EXISTS public.portal_academic_allocation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  UNIQUE (class_id, subject_id, teacher_id)
);

CREATE TABLE IF NOT EXISTS public.portal_timetable (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  day_of_week varchar(15) NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL
);

CREATE TABLE IF NOT EXISTS public.portal_attendance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  date date NOT NULL,
  status varchar(20) NOT NULL CHECK (status IN ('Present','Absent','Late','Medical_Leave')),
  marked_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  remarks varchar(255),
  UNIQUE (student_id, class_id, date)
);

CREATE TABLE IF NOT EXISTS public.portal_homework (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  title varchar(200) NOT NULL,
  description text NOT NULL,
  assigned_date date NOT NULL DEFAULT current_date,
  due_date date NOT NULL
);

CREATE TABLE IF NOT EXISTS public.portal_course (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  title varchar(200) NOT NULL,
  description text
);

CREATE TABLE IF NOT EXISTS public.portal_course_content (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id integer NOT NULL REFERENCES public.portal_course(id) ON DELETE CASCADE,
  content_type varchar(40) NOT NULL,
  title varchar(200) NOT NULL,
  resource_url text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.portal_assignment (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  teacher_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  title varchar(200) NOT NULL,
  description text NOT NULL,
  file_url text,
  max_marks integer NOT NULL DEFAULT 100,
  due_date timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.portal_assignment_submission (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id integer NOT NULL REFERENCES public.portal_assignment(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  submission_url text NOT NULL,
  submitted_at timestamptz NOT NULL DEFAULT now(),
  marks_obtained numeric,
  teacher_feedback text,
  UNIQUE (assignment_id, student_id)
);

CREATE TABLE IF NOT EXISTS public.portal_quiz (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id integer REFERENCES public.portal_course(id) ON DELETE CASCADE,
  title varchar(200) NOT NULL,
  duration_minutes integer NOT NULL DEFAULT 30,
  passing_score integer NOT NULL DEFAULT 40
);

CREATE TABLE IF NOT EXISTS public.portal_quiz_question (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id integer NOT NULL REFERENCES public.portal_quiz(id) ON DELETE CASCADE,
  question_text text NOT NULL,
  options jsonb NOT NULL DEFAULT '[]'::jsonb,
  correct_answer varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.portal_exam_schedule (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  teacher_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  exam_name varchar(200) NOT NULL,
  exam_type varchar(50) NOT NULL DEFAULT 'Unit_Test',
  exam_date date NOT NULL,
  start_time time NOT NULL DEFAULT '09:00',
  duration_minutes integer NOT NULL DEFAULT 60,
  max_marks integer NOT NULL DEFAULT 100
);

CREATE TABLE IF NOT EXISTS public.portal_hall_ticket (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  exam_schedule_id integer NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  ticket_number varchar(100) UNIQUE NOT NULL,
  is_verified boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.portal_result (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  exam_schedule_id integer NOT NULL REFERENCES public.portal_exam_schedule(id) ON DELETE CASCADE,
  marks_obtained numeric NOT NULL,
  rank_position integer,
  grade_points numeric,
  grade_letter varchar(10),
  remarks varchar(255),
  UNIQUE (student_id, exam_schedule_id)
);

CREATE TABLE IF NOT EXISTS public.portal_fee_structure (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer NOT NULL REFERENCES public.portal_class(id) ON DELETE CASCADE,
  term_name varchar(100) NOT NULL,
  tuition_fee numeric NOT NULL DEFAULT 0,
  transport_fee numeric NOT NULL DEFAULT 0,
  hostel_fee numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.portal_payment (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  fee_structure_id integer NOT NULL REFERENCES public.portal_fee_structure(id) ON DELETE CASCADE,
  transaction_id varchar(100) UNIQUE NOT NULL,
  amount_paid numeric NOT NULL,
  payment_method varchar(40) NOT NULL DEFAULT 'Online',
  status varchar(30) NOT NULL DEFAULT 'Success',
  paid_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.portal_book (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(255) NOT NULL,
  author varchar(255) NOT NULL,
  isbn varchar(50) UNIQUE,
  barcode_id varchar(100) UNIQUE,
  quantity integer NOT NULL DEFAULT 1,
  available_quantity integer NOT NULL DEFAULT 1,
  book_type varchar(30) NOT NULL DEFAULT 'Physical',
  digital_file_url text
);

CREATE TABLE IF NOT EXISTS public.portal_library_transaction (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id integer NOT NULL REFERENCES public.portal_book(id) ON DELETE CASCADE,
  borrower_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  issue_date date NOT NULL DEFAULT current_date,
  due_date date NOT NULL,
  return_date date,
  fine_amount numeric NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.portal_certificate (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  certificate_type varchar(100) NOT NULL,
  issued_date date NOT NULL DEFAULT current_date,
  file_url text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.portal_notification (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  recipient_type varchar(30) NOT NULL DEFAULT 'All',
  target_class_id integer REFERENCES public.portal_class(id) ON DELETE SET NULL,
  title varchar(200) NOT NULL,
  message text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.portal_question_bank (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id integer NOT NULL REFERENCES public.portal_subject(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  difficulty_level varchar(30) NOT NULL DEFAULT 'Medium',
  question_text text NOT NULL,
  answer_schema jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.portal_leave (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  leave_type varchar(50) NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  reason text NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'Pending',
  approved_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.portal_message (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  receiver_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  message_text text NOT NULL,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.portal_teacher_document (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  class_id integer REFERENCES public.portal_class(id) ON DELETE SET NULL,
  subject_id integer REFERENCES public.portal_subject(id) ON DELETE SET NULL,
  content_type varchar(40) NOT NULL DEFAULT 'PDF_Notes',
  title varchar(200) NOT NULL,
  resource_url text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_portal_profile_type ON public.portal_user_profile(user_type);
CREATE INDEX IF NOT EXISTS idx_portal_enrollment_student ON public.portal_student_enrollment(student_id);
CREATE INDEX IF NOT EXISTS idx_portal_allocation_teacher ON public.portal_academic_allocation(teacher_id);
CREATE INDEX IF NOT EXISTS idx_portal_attendance_student_date ON public.portal_attendance(student_id, date);
CREATE INDEX IF NOT EXISTS idx_portal_message_users ON public.portal_message(sender_id, receiver_id);
