# Generated by Django 5.0.6 on 2026-07-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_add_admin_portal_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionenquiry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
